### ISSUE TITLE
Add types/validation for matches

### ISSUE THREAD

**Issue by brookslybrand** [remix-run/remix-website#109]
`useMatches` and other cases of matches don't supply any types. With the v2 upgrade, this ended up causing TS to start failing. Added a bunch of `@ts-expect-error` statements with the intention of coming back and fixing them

If using `zod` makes this easy, that's great since we already have it in this project. However, avoid using it in any data that ships to the client (so server-side only)

**Comment by Kazuhiro-Mimaki** [comment]
Could I do this?

**Comment by takagimeow** [comment]
@brookslybrand 
Since the PR related to this issue has been merged, I believe this issue should be closed!

**Comment by brookslybrand** [comment]
Yep! Thanks for pointing that out

Fixed in #175
