### ISSUE TITLE
Create meta tag helper function

### ISSUE THREAD

**Issue by brookslybrand** [remix-run/remix-website#113]
Would be nice to have a common set of meta tags that we can use/extend. Maybe just a simple function with some defaults.

The main page (`_marketing._index.tsx`) has a nice set of defaults

```ts
export const meta: MetaFunction<typeof loader> = (args) => {
  let { siteUrl } = args.data || {};
  let title = "Remix - Build Better Websites";
  let image = siteUrl ? `${siteUrl}/img/og.1.jpg` : null;
  let description =
    "Remix is a full stack web framework that lets you focus on the user interface and work back through web standards to deliver a fast, slick, and resilient user experience. People are gonna love using your stuff.";
  return metaV1(args, {
    title,
    description,
    "og:url": siteUrl,
    "og:title": title,
    "og:description": description,
    "og:image": image,
    "twitter:card": "summary_large_image",
    "twitter:creator": "@remix_run",
    "twitter:site": "@remix_run",
    "twitter:title": title,
    "twitter:description": description,
    "twitter:image": image,
  });
};
```

I think we could possibly just extend this.

**Comment by Kazuhiro-Mimaki** [comment]
Since the PR related to this issue has been merged, I think this issue should be closed.

**Comment by brookslybrand** [comment]
@Kazuhiro-Mimaki thanks for pointing this out. The meta tags aren't completely cleaned up, but this was a good first step. I'll update the description of this issue, close it, and then create a new ticket for the remaining work

**Comment by brookslybrand** [comment]
See #214 for remaining work
