### ISSUE TITLE
Add search to mobile

### ISSUE THREAD

**Issue by brookslybrand** [remix-run/remix-website#117]
Right now our search bar is inaccessible on mobile. However, ~20% of docs users are accessing the docs on mobile devices (all time analytics)

<img width="480" alt="
Breakdown of visitors: Desktop - 772.9k, Phone - 158.2k, Tablet - 4.2k" src="https://github.com/remix-run/remix-website/assets/12396812/62fad4cf-0b54-4c24-8322-f9282d6b269b">

If if the number is less, it's worth figuring out a way to add the search bar for smaller screen sizes

**Comment by Kazuhiro-Mimaki** [comment]
Could I do this?
