### ISSUE TITLE
Add loading indicator to top nav

### ISSUE THREAD

**Issue by brookslybrand** [remix-run/remix-website#163]
A [suggestion](https://github.com/remix-run/remix-website/pull/162#issuecomment-1910814314) from @brophdawg11 

> we should add some form of loading indicators to the top nav (Docs, Blog, Showcase, Resources). I clicked on one that didn't have a cache entry so it took ~1-2s and there's no visual feedback that my click did anything

**Comment by sergiodxa** [comment]
@brookslybrand have you considered [nProgress](https://ricostacruz.com/nprogress/)? It's super simple but it's also similar to what some browsers like Safari shows when doing a MPA transition.

**Comment by brookslybrand** [comment]
@sergiodxa I have not really considered much of anything, just wanted to capture this comment real quick when Matt brought it up. That definitely looks like it could be a good option 👍

**Comment by gustavoguichard** [comment]
Would you be willing to have a Github-like progress bar like the one [on this post](https://dev.to/remix-run-br/creating-a-github-like-progress-bar-for-your-remix-app-153l) as a start?
I can work on this PR if welcomed.

**Comment by gustavoguichard** [comment]
I'll send it this weekend ;)

**Comment by stephenwade** [comment]
I think this issue can be closed.
