### ISSUE TITLE
Upgrade to Remix 2.6.0

### ISSUE THREAD

**Issue by fernandocanizo** [remix-run/remix-website#168]
Quoting from the blog post [Open Sourcing the Remix Website
](https://remix.run/blog/oss-remix-dot-run)

> We invite you to explore and learn from the [source code](https://github.com/remix-run/remix-website)
> ...
> Open sourcing our website allows us to provide a real-world Remix site to learn from

I believe that if one of the ideas is to provide a real-world working site, it would be better to do it with the latest version of Remix.

Currently the website is using 2.5.1

I haven't used Vite so far, I'm waiting for it to become stable-stable to start using it on my projects, but I don't mind giving it a shot if you need help with this upgrade. I love solving issues :)

**Comment by brookslybrand** [comment]
@fernandocanizo go for it! v2.6.0 was updated yesterday, and comes with a few breaking changes to the unstable `vite` plugin. The website being on `vite` is a big way we dogfood the `vite` compiler, so it will be good to make these changes
