### ISSUE TITLE
Vite config has hard-coded the .env file to the example file

### ISSUE THREAD

**Issue by fernandocanizo** [remix-run/remix-website#171]
File `vitest.config.mts` is the only place where `dotenv` is used and this is the code excerpt:

```
let env = dotenv.parse(
  fs.readFileSync(path.resolve(process.cwd(), ".env.example")),
);
```

As you can see, it has hardcoded the file to `.env.example` instead of reading from `.env`.

**Comment by brookslybrand** [comment]
Hey @fernandocanizo, as mentioned in #170, `vitest.config.mts` is for the testing framework, it's no the same thing as `vite.config.mts`, so it's fine that it's appropriate that it uses `.env.example`
