### ISSUE TITLE
Add RSS feed?

### ISSUE THREAD

**Issue by slorber** [remix-run/remix-website#182]
I'm surprised that the Remix does not have an RSS feed.
(but you are not alone see https://twitter.com/sebastienlorber/status/1754927448641135099)

Having an RSS feed would be useful for newsletter curators like me to notice new posts as soon as they are published, and feature them.

Alternatives are less "real-time" than having a proper RSS feed on your site:
- the Remix newsletter is not sent immediately after a new post
- the [Remix.guide](https://remix.guide/) site is apparently updated in batches
- using RSS reader "web feed" features is usually a paid option to track websites not having proper RSS feeds.

**Comment by brookslybrand** [comment]
Yep, I agree, thanks @slorber. Definitely something we should add to the blog
