### ISSUE TITLE
Bug: Resources README doesn't always render correctly

### ISSUE THREAD

**Issue by brookslybrand** [remix-run/remix-website#190]
See [Remix Fastify](https://remix.run/resources/remix-fastify) for an example

When I wrote the README fetcher for the Resource pages, I took a [naive approach](https://github.com/remix-run/remix-website/blob/main/app/lib/resources.server.ts#L107-L114)

Basically I'm assuming that the README url is always `main/readme.md`. This is not always true (see the Remix Fastify example).

The good thing is `octokit` will give you the appropriate URL with the following

```js
context.octokit.rest.repos.getReadme({ owner, repo })
```

All that's required is a little refactoring of code to fetch the correct content and the rendering should take care of itself

**Comment by HoldUpFjord** [comment]
Hey dude! I'd love to pick up this issue. Correct me if I'm wrong but in the current code: 

``async function fetchReadme(repo: string): Promise<string> {
  let md = await getRepoContent(repo, "main", "README.md");
  if (md === null) {
    throw Error(`Could not find README in ${repo}`);
  }
  let { html } = await processMarkdown(md);
  return html;
}``


We would want to refactor the second line to something like: `let md =await context.octokit.rest.repos.getReadme({ owner, repo });` Where we completely replace  `getRepoContent` and let octokit grab the proper README?

**Comment by brookslybrand** [comment]
Hey @HoldUpFjord, good to see you on here. 

Yeah pretty much, I think that should work. Bare in mind that’ll give you a lot more data than you need, so you’ll need to figure out how to pull out the appropriate content, or use the url it gives you and fetch that. I didn't look into it much further than that, so reach out if it’s still not clear

**Comment by brookslybrand** [comment]
Thanks @ovi-ispas, good point, doesn't seem like it gives you the URL after redirect right there. I think something like this should work though:

```ts
const readmeData = await context.octokit.rest.repos.getReadme({ owner, repo });
const readme = Buffer.from(readmeData.data.content, "base64").toString()
```

**Comment by mcansh** [comment]
😬 haha sorry for the trouble! the root README is an alias to the package's README to avoid copy and pasting the contents. GitHub serves the contents for the root readme as the aliased path when queried directly

**Comment by brookslybrand** [comment]
Thanks @mcansh! Honestly, glad your example pointed out the issue since it needed to be fixed, haha

**Comment by HoldUpFjord** [comment]
Hey I'm just catching up! I was planning on working on this over the weekend but it looks like @mcansh came up with really elegant solution. Great work dude, learned a lot from going over your comments & solution. 

@brookslybrand this issue considered closed? Or do you have a preferences on implementation towards your initial suggestion vs what Logan came up with?

**Comment by brookslybrand** [comment]
Thanks @HoldUpFjord! I'm reviewing @mcansh's PR now. It effects a lot more than the original scope of the issue, so I just want to do some due diligence first. Overall I prefer leaning on `octokit` for getting content given that it GitHub conventions (like these redirects) properly
