### ISSUE TITLE
Make doc sections collapsable

### ISSUE THREAD

**Issue by brookslybrand** [remix-run/remix-website#228]
We have _a lot_ of docs, so many that you can't see all the sections immediately

It would be really great to make the nav headers on the side collapsable. Also, need to make sure they're keyboard accessible

<img width="1800" alt="Screenshot 2024-03-20 at 10 52 55 AM" src="https://github.com/remix-run/remix-website/assets/12396812/9f223e31-2dcc-43b4-b56a-3937502e4e8c">

**Comment by sergiodxa** [comment]
The simplest way would be to use <details> tag

**Comment by seanmcquaid** [comment]
About to put up a PR for this!

**Comment by sergiodxa** [comment]
@seanmcquaid you don’t need to, you can fork the repo, push your branch to the fork and then open a PR from your repo to this repo

**Comment by seanmcquaid** [comment]
Awesome, thank you!! Might be worth adding to the docs as well!

**Comment by brookslybrand** [comment]
> Awesome, thank you!! Might be worth adding to the docs as well!

Thank for the suggestion! How does #235 look to you?
