### ISSUE TITLE
Remix website not working correctly

### ISSUE THREAD

**Issue by miradontsoa** [remix-run/remix-website#252]
Hi,

Appearantly, the remix website has some issues (date: 2024-04-06), root css, and som js does not load. 
Here is a screenshot.
![remix-2024-04-06](https://github.com/remix-run/remix-website/assets/5362814/de934789-aedd-4d40-a134-0cb1ccc43733)

**Comment by kandros** [comment]
It might be related to this https://x.com/brookslybrand/status/1776254267902304376?s=46

Does the problem persist after a refresh?

**Comment by herko** [comment]
> Does the problem persist after a refresh?

Yep. For me even when I disable caching in Dev tools - I get unstyled page an lots of 503 errors in console.

![Screenshot 2024-04-06 at 23 38 52](https://github.com/remix-run/remix-website/assets/1309343/184534d5-2435-462e-91c5-a794a3e65e81)

**Comment by miradontsoa** [comment]
> It might be related to this https://x.com/brookslybrand/status/1776254267902304376?s=46
> 
> Does the problem persist after a refresh?

It seems to work now, and this video explains everything. Thanks
