### ISSUE TITLE
Showcase page crashes with too many examples

### ISSUE THREAD

**Issue by brookslybrand** [remix-run/remix-website#273]
See #272 for initial quick fix

The video switching is honestly a bit buggier looking than I would like it to be on mobile, so that either needs to be reworked, or we just need to get rid of it entirely.

From my initial testing, its seems like the problem is also due to the number of resources. We need to look into if we're properly loading them or not.

**Comment by nikodunk** [comment]
FWIW, just checked the image-only version of the showcase currently deployed on mobile, and it feels calmer to me. Also, the videos take a _long_ time to make, tweak, edit to the right aspect ratio, export, get to seamlessly transition, etc. Esp. if you get feedback like I did. May be more scalable to have more traditional static images mid-term anyway. Less is sometimes more ;)

**Comment by brookslybrand** [comment]
Yeah @nikodunk, I tend to agree. It was fun building out the video version, but I'm not sure it results in a better UX

**Comment by brookslybrand** [comment]
I do still want the videos for desktop @nikodunk, so not sure we're getting away from the tediousness of creating the examples 😅 

Either way, I do think the mobile version needed to go, and I think I've resolved the underlying issue. Looking at #256 again now 👀
