### ISSUE TITLE
Fonts/words are laying on top of each other on the home page

### ISSUE THREAD

**Issue by anyuruf** [remix-run/remix-website#286]
Fonts/words are laying on top of each other on the home page on several sections. And that is on my 15.6 Inch Fedora Linux with Firefox browser. I have attached a png for clarity
![Screenshot_20240711_073746](https://github.com/remix-run/remix-website/assets/46653783/48e9b453-c1e5-4157-9b9b-3902de14aea8)
![Screenshot2](https://github.com/remix-run/remix-website/assets/46653783/d9aaf8ca-e8f7-46c8-ac0e-737009a2cfa2)
![Screenshot3](https://github.com/remix-run/remix-website/assets/46653783/8f9255d7-66cb-49f0-a81c-f2a26443152b)

**Comment by brookslybrand** [comment]
@anyuruf thanks for pointing this out and providing some screen shots!

I've gone ahead and implemented a fix in #290. Would you mind taking a look [at our staging site](https://remixdotrunstage.fly.dev/) and seeing if it fixes it for you?
